### ISSUE TITLE
enable global variables accross seperate injects within a script run

### ISSUE THREAD

**Issue by BenjaminGDH** [opentestingapi/hugo#2]
Hey Robert, currently the random generator variables of an inject are only available in the inject itself and follow-up checks or injects. They are not available in other injects within the inject list of the script that are triggered by their own cron-jobs. It would be great if overall testscenario relevant variable could be reused across all injects within a single testscript execution instance. 

BR, Ben

**Comment by robertdiers** [comment]
Hi Ben,
Should be possible - but we might end up with unexpected overrides. Not sure if we should make a difference between these use cases. Simply using the inherit feature is not sufficient? (Inherit should grab a variable from other inject and should duplicate it into the own "storage" - override will effect this one only)

**Comment by robertdiers** [comment]
Hi 

The feature request to use a central store for all injects or for the complete test case is not possible to realize. We do store the replacement data for every check / inject and the following actions (check or inject) are based on this data. It is possible to run multiple chains parallel to each other (for example cron every 3 sec, but hole execution takes up to one minute). We would end up having a lot of overrides including failed checks. Ever cron execution needs to be handled as a new "chain" with a defined set of randomly created data attributes. InheritFrom is our approach to load data from other chains, it is more a kind of a workaround as this also might create logical problems with overlapping executions.

Solution:
Instead of having multiple cron-activated injects you should use one only. Everything else should be within the "chain". If we need something like delay - that could be a valid feature request. For example "wait one minute after successful check to execute the inject".

Hope this helps - Robert

**Comment by robertdiers** [comment]
rejected

**Comment by BenjaminGDH** [comment]
Hey Robert, that sounds reasonable. I also used a single chain of subsequent injects as a workaround in the given case with a failing non-mandatory check inbetween to enforce a maxwaittime delay. Thus, an additional delay routine would be very helpful!
